language: java
deploy:
  provider: releases
  api_key:
    secure: exya/16wbwuMpDlwxrEDP7GfPrdeVzn1Z+dZ5aBDD0Je52cDxJWFT9bzSqiJ+UIIukIbV5RdNZ6VHwkoBszd2mgwOJ0dumYdoi5mHa/4JSwjIIz/JZfg/E36NACELujFp3GESzSwPWKpEP4SdYHLlli2b2cVuBqL9wy5GjB6hfg=
  file: abc
  on:
    repo: raskin-aleksandr/cloud-slang
